# Generated by Django 4.1.1 on 2022-12-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquestion',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
