# Generated by Django 4.1.1 on 2023-01-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_attributevalue_false_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='value',
            field=models.CharField(max_length=20),
        ),
    ]
