# Generated by Django 4.1.1 on 2023-02-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_delete_attributevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
