# Generated by Django 4.1.1 on 2023-02-19 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderline_status'),
        ('products', '0012_alter_productreview_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='order_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderline'),
        ),
    ]
