# Generated by Django 4.1.1 on 2023-02-19 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productreview_order_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='order_line',
        ),
    ]
