# Generated by Django 4.1.1 on 2023-02-19 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderline_status'),
        ('products', '0014_remove_productreview_order_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='order_line',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderline'),
        ),
    ]
