# Generated by Django 4.1.1 on 2023-02-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productreview_order_line'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productreview',
            name='unique_product_review',
        ),
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.UniqueConstraint(fields=('order_line', 'reviewer'), name='unique_product_review'),
        ),
    ]
