# Generated by Django 4.1.1 on 2023-03-02 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_billing_address',
            field=models.ForeignKey(limit_choices_to={'type': 'billing'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='billing_address', to='users.profileaddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profilepayment'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_shipping_address',
            field=models.ForeignKey(limit_choices_to={'type': 'shipping'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipping_address', to='users.profileaddress'),
        ),
    ]
