# Generated by Django 4.1.1 on 2023-01-14 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_price'),
        ('orders', '0002_shoppingcart_shoppingcartline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', unique=True),
        ),
        migrations.AlterField(
            model_name='shoppingcartline',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
