# Generated by Django 4.1.1 on 2023-01-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_customer_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='discount',
            field=models.FloatField(blank=True),
        ),
    ]
