# Generated by Django 4.1.1 on 2023-01-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_shoppingcartline_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartline',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shoppingcartline',
            name='shpping_cart',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
        migrations.DeleteModel(
            name='ShoppingCartLine',
        ),
    ]
