# Generated by Django 4.1.1 on 2023-01-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderline_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_taxes',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
