# Generated by Django 4.1.1 on 2023-01-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderline_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='status',
            field=models.CharField(choices=[('to_ship', 'To Ship'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='to_ship', max_length=15),
        ),
    ]
