# Generated by Django 4.1.1 on 2023-01-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderline_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='status',
            field=models.CharField(choices=[('to_ship', 'To Ship'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('waiting_customer_validation', 'Waiting Customer Validation')], default='to_ship', max_length=30),
        ),
    ]
