# Generated by Django 4.1.1 on 2023-02-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orderline_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='status',
            field=models.CharField(choices=[('to_ship', 'To Ship'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='to_ship', max_length=30),
        ),
    ]
