# Generated by Django 4.1.1 on 2023-01-02 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileaddress',
            old_name='numbwe',
            new_name='number',
        ),
    ]
