# Generated by Django 4.1.1 on 2022-12-30 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import apps.users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='users/pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfilePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('credit', 'Credit Card'), ('debit', 'Debit Card'), ('cash', 'Cash')], default='cash', max_length=50)),
                ('card_number', models.CharField(blank=True, max_length=16, unique=True, validators=[apps.users.models.only_numbers])),
                ('card_expiration_date', models.CharField(blank=True, max_length=5)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'verbose_name': 'Profile Payment',
                'verbose_name_plural': 'Profile Payments',
            },
        ),
        migrations.CreateModel(
            name='ProfileAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing')], default='shipping', max_length=20)),
                ('main_street', models.CharField(max_length=100)),
                ('numbwe', models.PositiveSmallIntegerField()),
                ('secondary_street', models.CharField(max_length=100)),
                ('zip_code', models.PositiveSmallIntegerField()),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'verbose_name': 'Profile Address',
                'verbose_name_plural': 'Profile Addresses',
            },
        ),
    ]
