# Generated by Django 4.1.1 on 2023-01-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profilepayment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileaddress',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profileaddress',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profileaddress',
            name='secondary_street',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
