# Generated by Django 4.1.1 on 2023-01-22 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_shoppingcart_shoppingcartline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileaddress',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='profilepayment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_cards', to='users.profile'),
        ),
    ]
