# Generated by Django 4.1.1 on 2023-01-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profileaddress_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepayment',
            name='card_provider',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
