# Generated by Django 4.1.1 on 2023-02-26 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profilepayment_card_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepayment',
            name='card_expiration_month',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='profilepayment',
            name='card_expiration_year',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1970)]),
        ),
    ]
