# Generated by Django 4.1.1 on 2023-03-02 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profilepayment_card_expiration_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepayment',
            name='card_expiration_date',
        ),
    ]
