# Generated by Django 4.1.1 on 2022-12-30 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField()),
                ('total_taxes', models.FloatField()),
                ('total', models.FloatField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid'), ('on_ship', 'On Ship'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='users.profile')),
                ('customer_billing_address', models.ForeignKey(limit_choices_to={'profile': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='users.profile'), 'type': 'billing'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='billing_addres', to='users.profileaddress')),
                ('customer_payment', models.ForeignKey(limit_choices_to={'profile': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='users.profile')}, on_delete=django.db.models.deletion.CASCADE, to='users.profilepayment')),
                ('customer_shipping_address', models.ForeignKey(limit_choices_to={'profile': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='users.profile'), 'type': 'shipping'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipping_address', to='users.profileaddress')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='users.profile')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='SaleOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('discount', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('line_total', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.saleorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Order Line',
                'verbose_name_plural': 'Order Lines',
            },
        ),
    ]
