# Generated by Django 4.1.1 on 2022-12-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='value',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
